/**
 * Attendance.js
 * -----------------------------------------------------------------------
 * Stores attendance generated by the Python face-recognition engine.
 * -----------------------------------------------------------------------
 */

const mongoose = require("mongoose");

const attendanceSchema = new mongoose.Schema(
  {
    studentId: {
      type: String,
      required: true,
      trim: true,
    },

    name: {
      type: String,
      required: true,
      trim: true,
    },

    date: {
      type: String,
      required: true,
      trim: true,
    },

    time: {
      type: String,
      required: true,
      trim: true,
    },

    status: {
      type: String,
      required: true,
      enum: ["Present", "Absent"],
      default: "Present",
    },

    trackId: {
      type: Number,
      required: true,
    },

    similarity: {
      type: Number,
      required: true,
      min: 0,
      max: 1,
    },
  },
  {
    timestamps: true,
  }
);

// ---------------------------------------------------------
// Prevent duplicate attendance for the same student/date
// ---------------------------------------------------------

attendanceSchema.index(
  {
    studentId: 1,
    date: 1,
  },
  {
    unique: true,
  }
);

module.exports = mongoose.model(
  "Attendance",
  attendanceSchema
);